version: '3'
services:
  default:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  simple:
    build:
      context: ''
      dockerfile: simple.Dockerfile
    ports:
      - 4000:80